import { useState } from 'react';
import './NCRPStepper.css';

const STEPS = [
  { label: 'Copy Complaint', icon: '📋' },
  { label: 'File on NCRP',   icon: '🌐' },
  { label: 'Evidence List',  icon: '📎' },
];

export default function NCRPStepper({ report }) {
  const [step, setStep] = useState(0);
  const [copied, setCopied] = useState(false);

  if (!report) return null;

  const incidentType   = report.incident_details?.type_of_fraud || 'Cyber Fraud';
  const riskLevel      = report.risk_assessment?.risk_level || 'Unknown';
  const description    = report.incident_details?.description || '';
  const redFlags       = report.incident_details?.red_flags || [];
  const complaintText  = `NCRP CYBERCRIME COMPLAINT
=========================
Complaint ID    : ${report.complaint_id}
Date            : ${report.complaint_date}
Complaint Type  : ${report.complaint_type}

FRAUD TYPE      : ${incidentType}
RISK LEVEL      : ${riskLevel}

INCIDENT DESCRIPTION:
${description}

RED FLAGS IDENTIFIED:
${redFlags.map((f, i) => `${i + 1}. ${f}`).join('\n')}

ACTION RECOMMENDED:
${report.action_recommended || 'Report immediately to cybercrime.gov.in'}

--- Generated by FraudNet — Citizen Fraud Shield ---`;

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(complaintText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (_) {}
  }

  return (
    <div className="ncrp-container">
      <div className="ncrp-header">
        <h3 className="ncrp-title">📝 File NCRP Complaint</h3>
        <p className="ncrp-subtitle">Follow these steps to report this fraud to authorities</p>
      </div>

      {/* Step tabs */}
      <div className="ncrp-tabs">
        {STEPS.map((s, i) => (
          <button
            key={i}
            className={`ncrp-tab ${step === i ? 'ncrp-tab-active' : ''}`}
            onClick={() => setStep(i)}
          >
            {s.icon} {s.label}
          </button>
        ))}
      </div>

      {/* Step content */}
      <div className="ncrp-body">
        {step === 0 && (
          <div className="ncrp-step">
            <p className="ncrp-step-desc">Your pre-filled complaint is ready. Copy it to submit on the NCRP portal.</p>
            <pre className="ncrp-complaint-text">{complaintText}</pre>
            <button className="ncrp-btn" onClick={handleCopy}>
              {copied ? '✅ Copied!' : '📋 Copy to Clipboard'}
            </button>
          </div>
        )}

        {step === 1 && (
          <div className="ncrp-step">
            <p className="ncrp-step-desc">File your complaint on the official National Cyber Crime Reporting Portal.</p>
            <div className="ncrp-guide">
              <div className="ncrp-guide-step">
                <span className="ncrp-guide-num">1</span>
                <span>Visit <strong>cybercrime.gov.in</strong> and click <em>"Report Cybercrime"</em></span>
              </div>
              <div className="ncrp-guide-step">
                <span className="ncrp-guide-num">2</span>
                <span>Select <strong>"Other Cyber Crimes"</strong> → <strong>"{incidentType}"</strong></span>
              </div>
              <div className="ncrp-guide-step">
                <span className="ncrp-guide-num">3</span>
                <span>Paste the complaint text you copied in Step 1</span>
              </div>
              <div className="ncrp-guide-step">
                <span className="ncrp-guide-num">4</span>
                <span>Attach screenshots or evidence files</span>
              </div>
              <div className="ncrp-guide-step">
                <span className="ncrp-guide-num">5</span>
                <span>Submit and note your complaint reference number</span>
              </div>
            </div>
            <a
              href="https://www.cybercrime.gov.in"
              target="_blank"
              rel="noopener noreferrer"
              className="ncrp-btn ncrp-btn-link"
            >
              🌐 Open cybercrime.gov.in →
            </a>
          </div>
        )}

        {step === 2 && (
          <div className="ncrp-step">
            <p className="ncrp-step-desc">Gather this evidence before filing to strengthen your complaint.</p>
            <div className="ncrp-checklist">
              {[
                'Screenshot of the suspicious message / call',
                'Phone number or UPI ID used by the fraudster',
                'Transaction ID or bank statement (if money was lost)',
                'Any URLs or links shared by the fraudster',
                'Your own name, phone number, and email for complaint',
                'Date and time of the incident',
              ].map((item, i) => (
                <EvidenceItem key={i} text={item} />
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function EvidenceItem({ text }) {
  const [checked, setChecked] = useState(false);
  return (
    <label className={`ncrp-check-item ${checked ? 'ncrp-checked' : ''}`}>
      <input type="checkbox" checked={checked} onChange={() => setChecked(!checked)} />
      <span>{text}</span>
    </label>
  );
}
